name: Sync Submodule

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  Sync-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Set Locale to UTF-8
        run: |
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8
          export LANG=en_US.UTF-8
          export LANGUAGE=en_US.UTF-8
          export LC_ALL=en_US.UTF-8


      - name: Checkout main repository
        uses: actions/checkout@v4.2.0
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update all submodules
        run: |
          git submodule foreach --recursive 'git checkout main && git pull origin main'

      - name: Commit changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config --global user.email "glebmavi@gmail.com"
            git config --global user.name "Gleb Malikov Villegas ^_^"
            git add .
            git commit -m "Update submodules to latest commits"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}